version: 2
jobs:

  install:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Running Tests
          command: yarn run test

  build-linux:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Installing node-gyp
          command: sudo npm install -g node-gyp
      - run:
          name: Building with node-gyp
          command: node-gyp configure && node-gyp build
      - run:
          name: Create Final Directory
          command: mkdir ./final
      - run:
          name: Rename File
          command: mv ./build/Release/nsfw.node ./final/nsfw-linux.node
      - store_artifacts:
          path: final/nsfw-linux.node
      - persist_to_workspace:
          root: .
          paths:
            - final/nsfw-linux.node

  build-alpine:
    docker:
      - image: mhart/alpine-node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing apk dependencies
          command: apk add --no-cache ca-certificates build-base python
      - attach_workspace:
          at: .
      - run:
          name: Installing node-gyp
          command: npm install -g node-gyp --unsafe-perm=true
      - run:
          name: Building with node-gyp
          command: node-gyp configure && node-gyp build
      - run:
          name: Create Final Directory
          command: mkdir ./final
      - run:
          name: Rename File
          command: mv ./build/Release/nsfw.node ./final/nsfw-alpine.node
      - store_artifacts:
          path: final/nsfw-alpine.node
      - persist_to_workspace:
          root: .
          paths:
            - final/nsfw-alpine.node

  build-macos:
    macos:
      xcode: '10.2.0'
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Custom Node.js
          command: curl -sfLS https://install-node.now.sh/10.15.3 | bash -s -- --yes
      - run:
          name: Installing node-gyp
          command: sudo npm install -g node-gyp
      - run:
          name: Building with node-gyp
          command: node-gyp configure && node-gyp build
      - run:
          name: Create Final Directory
          command: mkdir ./final
      - run:
          name: Rename File
          command: mv ./build/Release/nsfw.node ./final/nsfw-macos.node
      - store_artifacts:
          path: final/nsfw-macos.node
      - persist_to_workspace:
          root: .
          paths:
            - final/nsfw-macos.node

  upload:
    docker:
      - image: circleci/golang:1.10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Installing Uploader
          command: go get github.com/aktau/github-release
      - run:
          name: Uploading Binaries
          command:
            >-
              for file in ./final/*.node;
              do
               github-release upload -R -t `git describe --tags` -n ${file##*/} -f $file
              done
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  publish:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Saving Authentication Information
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publishing to Stable Channel
          command: npm publish --tag latest

workflows:
  version: 2
  unscheduled:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build-linux:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - build-alpine:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - build-macos:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - upload:
          requires:
            - build-linux
            - build-macos
            - build-alpine
          filters:
            tags:
              only: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - upload
          filters:
            tags:
              only: /^(\d+\.)?(\d+\.)?(\*|\d+)$/
